# Generated by Django 6.0.4 on 2026-05-05 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='manufacturer_logos/')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('body_type', models.CharField(blank=True, choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('COUPE', 'Coupe'), ('HATCHBACK', 'Hatchback'), ('CONVERTIBLE', 'Convertible'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('WAGON', 'Wagon')], max_length=20)),
                ('fuel_type', models.CharField(blank=True, choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('PLUGIN_HYBRID', 'Plug-in Hybrid')], max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('CVT', 'CVT'), ('DUAL_CLUTCH', 'Dual-Clutch')], max_length=20)),
                ('engine_size', models.CharField(blank=True, help_text='e.g., 3.5L V6', max_length=50)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='inventory.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer', 'name', '-year'],
                'unique_together': {('manufacturer', 'name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('mileage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code, e.g., #FF0000', max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('PE', 'Sale Pending'), ('SO', 'Sold')], default='AV', max_length=2)),
                ('condition', models.CharField(choices=[('NEW', 'Brand New'), ('LN', 'Like New'), ('EX', 'Excellent'), ('GD', 'Good'), ('FR', 'Fair')], default='EX', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features, e.g., Sunroof, Leather Seats, NAV')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured vehicles appear on the homepage')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='inventory.carmodel')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='inventory.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_on'],
            },
        ),
    ]
